language: node_js
node_js:
  - "5"
  - "6"
  - "7"
matrix:
  include:
      env:
        - TEST="all"
        - CXX=g++-4.8
#notifications:
#  email:
#    - jchan@linkedin.com
#    - skinast@linkedin.com
before_install:
  - npm install -g npm@3
before_script:
  - npm update
sudo: false
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
- coveralls < tmp/coverage/lcov/lcov.info
